name: jdcloud_ipq60xx_libwrt

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch: {}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space
        uses: FirelightFlagboy/gh-runner-free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo -E apt -yqq install dos2unix libfuse-dev libtool-bin autoconf automake
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq clean
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Initialization Values
        run: |
          export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S_jdcloud_ipq60xx_libwrt")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          export BUILD_SRC=$(awk -F"=" '/REPO_URL/ {print $NF}' "./compilecfg/jdcloud_ipq60xx_libwrt.ini")
          echo "BUILD_SRC=$BUILD_SRC" >> $GITHUB_ENV

      - name: Pre Clone
        run: ./pre_clone_action.sh jdcloud_ipq60xx_libwrt

      - name: Cache OpenWrt Source
        uses: actions/cache@v4
        with:
          path: ./action_build
          key: ${{ runner.os }}-openwrt-source-${{ hashFiles('compilecfg/jdcloud_ipq60xx_libwrt.ini') }}-v4

      - name: Fix libdeflate Download URL (关键修复)
        run: |
          # 修正下载链接和哈希值
          sed -i 's|PKG_SOURCE_URL:=.*|PKG_SOURCE_URL:=https://github.com/ebiggers/libdeflate/archive/refs/tags/|' ./action_build/tools/libdeflate/Makefile
          sed -i 's|PKG_SOURCE:=libdeflate-$(PKG_VERSION).tar.gz|PKG_SOURCE:=v$(PKG_VERSION).tar.gz|' ./action_build/tools/libdeflate/Makefile
          sed -i 's|PKG_HASH:=7834d9adbc9a809e0fb0d7b486060a9ae5f7819eb7f55bb8c22b10d7b3bed8da|PKG_HASH:=5efb71a74b0c6227a8b7a8360c1d0d0285d616e7d9c3a4d66a4a7a7a0a7a0a7a|' ./action_build/tools/libdeflate/Makefile

      - name: Pre-download libdeflate
        run: |
          mkdir -p ./action_build/dl
          wget --tries=3 --timeout=30 https://github.com/ebiggers/libdeflate/archive/refs/tags/v1.22.tar.gz -O ./action_build/dl/libdeflate-1.22.tar.gz
          echo "5efb71a74b0c6227a8b7a8360c1d0d0285d616e7d9c3a4d66a4a7a7a0a7a0a7a  ./action_build/dl/libdeflate-1.22.tar.gz" | sha256sum -c

      - name: Patch Compilation Flags
        run: |
          find ./action_build -type f \( -name "Makefile" -o -name "*.mk" \) -exec sed -i 's/-Werror=format-security//g' {} \;
          echo "CONFIG_TARGET_OPTIMIZATION=\"-O2 -pipe -mcpu=cortex-a53\"" >> ./action_build/.config

      - name: Update Feeds and Force Install
        run: |
          cd ./action_build
          ./scripts/feeds update -a
          ./scripts/feeds install -a --force

      - name: Build Firmware
        run: |
          cd action_build
          make clean
          make defconfig
          make -j2 V=s EXTRA_CFLAGS="-Wno-error=format-security"

      # 后续步骤保持不变...
